// Serve an extracted PDF image from disk.
// GET /api/notebooks/:id/sources/:sid/images/:name

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { define } from "../../../../../../../utils.ts";
import { imagesDir } from "../../../../../../../lib/storage.ts";

export const handler = define.handlers({
  async GET(ctx) {
    const { id: notebookId, sid: sourceId, name } = ctx.params;
    // Hard guard against path traversal — names are generated by us as
    // `page-N-img-M.png` so anything else is rejected.
    if (!/^[a-zA-Z0-9._-]+$/.test(name)) {
      return new Response("Bad filename", { status: 400 });
    }
    const path = join(imagesDir(notebookId, sourceId), name);
    try {
      const bytes = await readFile(path);
      // Web's Response wants a BodyInit; Buffer→Uint8Array view is fine.
      const view = new Uint8Array(
        bytes.buffer,
        bytes.byteOffset,
        bytes.byteLength,
      );
      return new Response(view, {
        headers: {
          "Content-Type": name.endsWith(".png") ? "image/png" : "application/octet-stream",
          "Cache-Control": "private, max-age=3600",
        },
      });
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") {
        return new Response("Not found", { status: 404 });
      }
      throw err;
    }
  },
});
